# Generated by Django 5.2.6 on 2025-09-24 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='ФИО врача')),
                ('position', models.CharField(max_length=100, verbose_name='Должность')),
                ('category', models.CharField(max_length=50, verbose_name='Категория')),
                ('experience', models.CharField(max_length=50, verbose_name='Стаж')),
                ('bio', models.TextField(verbose_name='Биография')),
                ('education', models.TextField(verbose_name='Образование')),
                ('qualifications', models.TextField(verbose_name='Повышение квалификации')),
                ('photo', models.ImageField(upload_to='doctors/', verbose_name='Фотография')),
            ],
            options={
                'verbose_name': 'Врач',
                'verbose_name_plural': 'Врачи',
            },
        ),
        migrations.CreateModel(
            name='Promotion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Название акции')),
                ('description', models.TextField(verbose_name='Описание акции')),
                ('image', models.ImageField(upload_to='promotions/', verbose_name='Изображение')),
                ('start_date', models.DateField(verbose_name='Дата начала')),
                ('end_date', models.DateField(verbose_name='Дата окончания')),
            ],
            options={
                'verbose_name': 'Акция',
                'verbose_name_plural': 'Акции',
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=100, verbose_name='Автор отзыва')),
                ('text', models.TextField(verbose_name='Текст отзыва')),
                ('photo', models.ImageField(upload_to='reviews/', verbose_name='Фотография автора')),
                ('created_at', models.DateField(auto_now_add=True, verbose_name='Дата создания')),
            ],
            options={
                'verbose_name': 'Отзыв',
                'verbose_name_plural': 'Отзывы',
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название услуги')),
                ('description', models.TextField(verbose_name='Описание услуги')),
                ('icon', models.CharField(help_text='Имя класса Font Awesome', max_length=50, verbose_name='Иконка')),
            ],
            options={
                'verbose_name': 'Услуга',
                'verbose_name_plural': 'Услуги',
            },
        ),
    ]
